// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateCabs(ctx context.Context, arg CreateCabsParams) (Cab, error)
	CreateCustomer(ctx context.Context, arg CreateCustomerParams) (Customer, error)
	CreateDriver(ctx context.Context, arg CreateDriverParams) (Driver, error)
	DeleteCab(ctx context.Context, id uuid.UUID) error
	DeleteCustomer(ctx context.Context, id uuid.UUID) error
	DeleteDriver(ctx context.Context, username string) error
	GetCab(ctx context.Context, id uuid.UUID) (Cab, error)
	GetCustomer(ctx context.Context, id uuid.UUID) (Customer, error)
	GetDriver(ctx context.Context, id uuid.UUID) (Driver, error)
	UpdateCab(ctx context.Context, arg UpdateCabParams) (Cab, error)
	UpdateDriver(ctx context.Context, arg UpdateDriverParams) (Driver, error)
}

var _ Querier = (*Queries)(nil)
